"""
Collected shared NetPyNE parser core.

This first-pass module intentionally contains only the stable low-level parser
functions shared by the A1 and model_tuner lineages, plus a few small A1-sourced
NumPy helpers. Xarray adapters, sim_res_analyzer-only helpers, and
batch_osc-specific behavior are kept out of this parser-core module.
"""

from typing import Dict, List

import numpy as np


def get_pop_names(sim_result):
    return list(sim_result["net"]["pops"].keys())


def get_lfp_coords(sim_result):
    cfg = sim_result["simConfig"]
    lfp_coords = np.array(cfg["recordLFP"])
    return lfp_coords


def get_record_times(sim_result):
    cfg = sim_result["simConfig"]
    dt = cfg["recordStep"]
    T = cfg["duration"]
    tt = np.arange(0, T, dt)
    return tt


def get_lfp(sim_result):
    lfp = np.array(sim_result["simData"]["LFP"]).T
    lfp_coords = get_lfp_coords(sim_result)
    tt = get_record_times(sim_result)
    return lfp, tt, lfp_coords


def get_pop_lfps(sim_result):
    lfp = {}
    for pop_name, pop_lfp in sim_result["simData"]["LFPPops"].items():
        lfp[pop_name] = np.array(pop_lfp).T
    lfp_coords = get_lfp_coords(sim_result)
    tt = get_record_times(sim_result)
    return lfp, tt, lfp_coords


def get_pop_ylim(sim_res, pop_name):
    h = sim_res["simConfig"]["sizeY"]
    yy = sim_res["net"]["pops"][pop_name]["tags"]["ynormRange"]
    return (yy[0] * h, yy[1] * h)


def get_layer_borders(sim_result):
    layer_yrange = {}
    for pop_name in sim_result["net"]["pops"]:
        layer_yrange[pop_name] = get_pop_ylim(sim_result, pop_name)
    return layer_yrange


def get_net_params(sim_result):
    return sim_result["net"]["params"]


def get_pop_params(sim_result, pop_name=None):
    if pop_name is None:
        return get_net_params(sim_result)["popParams"]
    else:
        return get_net_params(sim_result)["popParams"][pop_name]


def get_pop_cell_gids(sim_result, pop_name):
    return sim_result["net"]["pops"][pop_name]["cellGids"]


def get_sim_data(sim_result):
    return sim_result["simData"]


def get_pop_size(sim_result, pop_name) -> int:
    return len(get_pop_cell_gids(sim_result, pop_name))


def get_net_size(sim_result) -> Dict[str, int]:
    return {pop_name: get_pop_size(sim_result, pop_name)
            for pop_name in get_pop_names(sim_result)}


def get_sim_duration(sim_result):
    return sim_result["simConfig"]["duration"] / 1000


def get_timestep(sim_result):
    return sim_result["simConfig"]["dt"] / 1000


def get_pop_spikes(sim_result, pop_name, combine_cells=True,
                   t0=0, tmax=None, subtract_t0=True, ms=False,
                   ndigits=6) -> List[np.ndarray]:
    """Get times of spikes generated by a given population."""
    sim_data = get_sim_data(sim_result)
    pop_cell_idx = get_pop_cell_gids(sim_result, pop_name)
    spike_cell_idx = np.array(sim_data["spkid"])
    spkt = np.array(sim_data["spkt"]) / 1000
    if tmax is None:
        tmax = get_sim_duration(sim_result)
    t_mask = (spkt >= t0) & (spkt <= tmax)
    tsub = t0 if subtract_t0 else 0
    mult = 1000 if ms else 1
    if combine_cells:
        pop_mask = np.isin(sim_data["spkid"], pop_cell_idx)
        spike_times = (spkt[pop_mask & t_mask] - tsub) * mult
        spike_times = [np.round(spike_times, ndigits)]
    else:
        spike_times = []
        for cell_id in pop_cell_idx:
            cell_mask = (spike_cell_idx == cell_id)
            s = (spkt[cell_mask & t_mask] - tsub) * mult
            s = np.round(s, ndigits)
            spike_times.append(s)
    return spike_times


def get_net_spikes(sim_result, pop_names=None, combine_cells=True,
                   t0=0, tmax=None, subtract_t0=True, ms=False,
                   ndigits=6) -> Dict[str, List[np.ndarray]]:
    """Get times of spikes generated by a given set of populations."""
    pop_names = pop_names or get_pop_names(sim_result)
    S = {}
    for pop_name in pop_names:
        S[pop_name] = get_pop_spikes(
            sim_result, pop_name, combine_cells, t0, tmax,
            subtract_t0, ms, ndigits=6
        )
    return S


def get_pop_voltages(sim_result, pop, t_limits=None):
    tvec = np.array(sim_result["simData"]["t"])
    if t_limits is not None:
        mask = (tvec >= t_limits[0]) & (tvec <= t_limits[1])
        tvec = tvec[mask]
    else:
        mask = np.ones_like(tvec, bool)

    gids = sorted(get_pop_cell_gids(sim_result, pop))

    V_map = {}
    for cell_name, V_vec in sim_result["simData"]["V_soma"].items():
        gid = int(cell_name.split("_")[-1])
        if gid in gids:
            V_map[gid] = np.array(V_vec)[mask]

    vv = [V_map[gid] for gid in gids if gid in V_map]
    V = np.stack(vv, axis=0)

    return V, tvec


def get_voltages(sim_result, t_limits=None):
    pop_names = get_pop_names(sim_result)

    tvec = np.array(sim_result["simData"]["t"])
    if t_limits is not None:
        mask = (tvec >= t_limits[0]) & (tvec <= t_limits[1])
        tvec = tvec[mask]
    else:
        mask = np.ones_like(tvec, bool)

    V_map = {}
    for cell_name, V_vec in sim_result["simData"]["V_soma"].items():
        gid = int(cell_name.split("_")[-1])
        V_map[gid] = np.array(V_vec)[mask]

    pop_gids = {pop: get_pop_cell_gids(sim_result, pop)
                for pop in pop_names}

    V_data = {}
    for pop in pop_names:
        gids = sorted(pop_gids[pop])
        vv = [V_map[gid] for gid in gids if gid in V_map]
        V_data[pop] = np.stack(vv, axis=0)

    return V_data, tvec
